### ISSUE TITLE
Chat in Lobbies

### ISSUE THREAD

**Issue by SamuelLabrador** [SamuelLabrador/SecurityTrader#16]
As a user, I'd like to be able to chat with other players while I'm playing a game.

Definition of Done
- [x] Sending messages to chat should happen over a WebSocket connection
- [x] Receiving messages should happen over a WebSocket connection
- [x] When a player sends a message, all the people in the same lobby should receive that message. 
- [x] Messages should be displayed with a timestamp for when they are sent.

Some additional notes:
- Chat does not need to be logged to a database table at the moment. In the future, we plan on logging chat messages with their associated user.

**Comment by SamuelLabrador** [comment]
Draft Player Actor System
@miguelandrade4 

![actor_architecture](https://user-images.githubusercontent.com/32395888/107110159-883b3a80-67fa-11eb-97de-aa07efceeec5.png)
